# Generated by Django 3.2.3 on 2026-02-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='', null=True, upload_to='users/avatars/', verbose_name='Аватар'),
        ),
    ]
